# Generated by Django 4.0.6 on 2022-08-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
